---
title: constrain()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= constrain(x, a, b)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Constrains a number to be within a range.
[%hardbreaks]


[float]
=== Syntax
`constrain(x, a, b)`


[float]
=== Parameters
`x`: the number to constrain Allowed data types: all data types. +
`a`: the lower end of the range. Allowed data types: all data types. +
`b`: the upper end of the range. Allowed data types: all data types.


[float]
=== Returns
x: if x is between a and b. +
a: if x is less than a. +
b: if x is greater than b.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code limits the sensor values to between 10 to 150.

[source,arduino]
----
sensVal = constrain(sensVal, 10, 150);  // limits range of sensor values to between 10 and 150
----

[float]
=== Notes and Warnings
Because of the way the `constrain()` is implemented, avoid using function calls and expressions inside the brackets, it will lead to incorrect behaviour.

This code will not work as expected:
[source,arduino]
----
int constrainedInput1 = constrain(Serial.parseInt(), minimumValue, maximumValue);   // don't do this
value = constrain(value++, minimumValue, maximumValue);   // also don't do this
----

Because `constrain(x, a, b)` may _evaluate_ its parameters more than once.

Evaluate in this example means it's possible that `Serial.parseInt()` will get called more than once, which isn't obvious from looking at the source code.

To be safe, always use `constrain()` with either fixed values or a list of variable names like this:
[source,arduino]
----
int input = Serial.parseInt();  // keep other operations outside the constrain function
int constrainedInput = constrain(input, minimumValue, maximumValue);
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

--
// SEE ALSO SECTION ENDS
